GET http://localhost:5001/authenticated HTTP/1.1
Authorization: Bearer my-token

###
GET http://localhost:5001/logger HTTP/1.1

###
PUT http://localhost:5001/users/1 HTTP/1.1
Content-Type: application/json

{
  "name": ""
}